### PR TITLE
Adding static pages for PAFS

### PR DESCRIPTION
**Pull request by nigejohnson**
Adding static pages for PAFS

### CODE REVIEW

**Review by Cruikshanks — CHANGES_REQUESTED** [review]
Testing it locally the images in the footer are not coming through for the back office pages.

Also it makes it easier to check if links to the pages are added to `index.html`, that way you can just go to <http://localhost:8000> and click on the page of interest.

Final one is not critical, but I understood the aim was to style the back office pages the same as the front office. Just in case you hadn't spotted, the font is actually different. So if you wanted it exactly the same you might want to check what font is being used for the back office pages.

Other than that all seems fine as far as I can see 😁 !

**Comment by Cruikshanks** [comment]
As requested have double checked the pages @nigejohnson . This time I just opened them directly rather than running the Python web server (details in the README)

## Missing images

I'm still not getting any images across all the browsers I have installed.

**Chrome Version 56.0.2924.87 (64-bit)**
screen shot 2017-03-03 at 13 47 58

**Safari Version 10.0.3 (10602.4.8.0.1)**
screen shot 2017-03-03 at 13 49 16

**Firefox 44.0**
screen shot 2017-03-03 at 13 52 01

I've shown `pafs-bo-unavailable.html` but the same is true for `pafs-bo-maintenance.html`.

## Font

On the font hopefully the following side by side is clear enough to demonstrate what I'm seeing.

pafs_static_font_comparison

On the left is a back office page, on the right is a front office. I don't actually think its critical, but the difference was immediately obvious to me, so worth highlighting if the aim was that they should be the same.

## Index page

I'd still like to see links to these pages added to [index.html](index.html) as it makes working with the project easier, and is a handy list of contents to new people to the project

## Summary

I can't approve the changes whilst I'm still seeing missing images. I've tried both loading files directly and when served from the Python web server, and across a range of browsers. Also tried on someone else's machine with the same result.

The index page needs updating, but I leave the difference in fonts as a decision for the team as to how much time you invest in trying to make them the same.

Ideally the PAFS back office should have used the GDS admin template so that it is consistent with some of our other services. But as you have gone down a different road I don't see any problem with having a `back-office-pafs` folder at the root, into which you essentially copy all the front end assets and pages, updated with back office wording. That would solve all the discrepancies issues, and leave the existing back-office stuff untouched. What do you :thinking: 💭 ?

**Comment by Cruikshanks** [comment]
Now we've merged #4 we can probably close this one @nigejohnson . If you're happy with this I'll leave you to do the honours.

**Comment by nigejohnson** [comment]
Superseded by a later PR, so closing.

**Pull request closed without merging**
