### PR TITLE
Add PAFS static service pages

### PR DESCRIPTION
**Pull request by Cruikshanks**
https://eaflood.atlassian.net/browse/PM-235

The **Project application and funding service** (PAFS) is expected to be the next digital service to go beta public and therefore they require new static service pages.

This covers the addition of those pages to the project.

### CODE REVIEW

**Comment by Cruikshanks** [comment]
Raised this PR as a alternative to #3 , with the benefit that this addresses the issues raised in #3 .

When testing all images came through on all pages, and things like the fonts are consistent throughout.

## Front office

### Maintenance
pafs-fo-maintenance

### Unavailable
pafs-fo-unavailable

## Back office

### Maintenance
pafs-bo-maintenance

### Unavailable
pafs-bo-unavailable

**Comment by Cruikshanks** [comment]
What do you think to this @nigejohnson ? This might shortcut the need for trying to dig into css/html and trying to figure out why an image isn't coming through. We can then put this story behind us! 😁

**Comment by nigejohnson** [comment]
Hi Alan,

So have you restricted that repo along the lines you suggested to create a special PAFs BO area? (Thus avoiding the having to copy everything FO into the BO folders to make the PAFS BO pages look FO)?

Is that what you’ve done?

(Agree this has been mighty tiresome!).

Regards,

Nigel.

**Comment by Cruikshanks** [comment]
Sort of. On review I decided against a whole new area (i.e. folder) just for PAFS because assuming at some point in the future we update the assets to match the latest version of GOV.UK, we'd have to do that twice.

So the simplest, cleanest solution I saw was to put all the PAFS pages in the [front-office](/front-office) folder, but also provide the ability to record why something doesn't appear to be following convention (see the new CONTRIBUTING.md#convention-breaks section).

**Comment by nigejohnson** [comment]
Yes, that was my plan B too (but I’m not going to explain it to the rest of the PAFS team ☺ or I’ll lose the will to live.)

I think we just came a cropper because PAFs was insistent on keeping the FO styles for even the BO out of service pages, that didn’t match the repo structure putting me into a dilemma, you were on a course and no one else would or could advise as to how best to resolve that dilemma, combined with PAFS having to have something last minute for their assessment. None of that was of our doing though we are the ones who’ve been poked excessively! ☺.

Have any of the actual pages been changed? If so we’ll have to get Imran to redeploy and retest (to ensure what’s out there actually matches what’s in the repo).

Thanks,

Nigel.

**Comment by Cruikshanks** [comment]
Completely understand, hence one of the changes included in this PR is to add a CONTRIBUTING.md document so hopefully others aren't put in that position.

Regards web-ops and testing as these pages (both back and front) are simply copy and paste versions of existing service pages we know do work, and Phil has confirmed he's happy with the content, we can just focus on the code. So as long as you can see these pages ok from your machine, and you are happy with the changes, we can approve this PR and get it merged in.

Web-ops can then point whatever they have setup to the project proper (i.e. `master` branch) and update it. Finally we can then confirm the latest version of the service pages are working for pafs.

**Review by nigejohnson — COMMENTED** [review]
How do a pull or fetch this branch in order to test it?
When I do git branch -a I can't see it...only master and the Static_service_pages_for_pafs branch.

**Comment by nigejohnson** [comment]
Hi Alan,
I've pulled these down and given them a quick test now: all seems fine to me, so I merged the pull request. Can you ask Imran to do whatever it is he needs to do to pull the 4 pages back out of this repo and redeploy them, so that Howard and Imran can give them a quick re-test again please? (As the I'm guessing the pages will be different from what's already been tested).
Thanks,
Nigel.

**Pull request merged**
